import type { Product, CategoryInfo } from "./types";

export const categories: CategoryInfo[] = [
  {
    id: "apparel",
    label: "Apparel",
    image: "https://images.pexels.com/photos/22441297/pexels-photo-22441297.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    description: "Elevated everyday essentials",
  },
  {
    id: "footwear",
    label: "Footwear",
    image: "https://images.pexels.com/photos/18155788/pexels-photo-18155788.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    description: "Crafted for movement",
  },
  {
    id: "accessories",
    label: "Accessories",
    image: "https://images.pexels.com/photos/33109351/pexels-photo-33109351.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    description: "The finishing touch",
  },
  {
    id: "home",
    label: "Home",
    image: "https://images.pexels.com/photos/4202326/pexels-photo-4202326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    description: "Objects with intention",
  },
];

const sizeApparel = ["XS", "S", "M", "L", "XL"];
const sizeFootwear = ["7", "8", "9", "10", "11", "12"];
const sizeOneSize = ["One Size"];

export const products: Product[] = [
  {
    id: "p1",
    name: "Heritage Linen Shirt",
    brand: "LUMEN",
    price: 128,
    category: "apparel",
    image: "https://images.pexels.com/photos/22441297/pexels-photo-22441297.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/22441297/pexels-photo-22441297.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/22441295/pexels-photo-22441295.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/22441292/pexels-photo-22441292.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Natural", hex: "#e7e5e4" },
      { name: "Black", hex: "#1c1917" },
      { name: "Sage", hex: "#a3b18a" },
    ],
    sizes: sizeApparel,
    description: "A breathable linen shirt with a relaxed drape, cut from premium European flax. Designed to live in, season after season.",
    details: ["100% European flax linen", "Mother-of-pearl buttons", "Relaxed fit", "Machine washable cold"],
    rating: 4.8,
    reviewCount: 214,
    badge: "bestseller",
  },
  {
    id: "p2",
    name: "Everyday White Tee",
    brand: "LUMEN",
    price: 48,
    compareAtPrice: 65,
    category: "apparel",
    image: "https://images.pexels.com/photos/9558761/pexels-photo-9558761.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/9558761/pexels-photo-9558761.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/8408556/pexels-photo-8408556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "White", hex: "#f5f5f4" },
      { name: "Blush", hex: "#f8d7da" },
    ],
    sizes: sizeApparel,
    description: "The perfect weight cotton tee â€” substantial enough to hold its shape, soft enough to forget you're wearing it.",
    details: ["Organic supima cotton", "Pre-shrunk", "Reinforced collar", "Garment dyed"],
    rating: 4.9,
    reviewCount: 532,
    badge: "sale",
  },
  {
    id: "p3",
    name: "Selvedge Denim Jeans",
    brand: "LUMEN",
    price: 165,
    category: "apparel",
    image: "https://images.pexels.com/photos/10133274/pexels-photo-10133274.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/10133274/pexels-photo-10133274.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Indigo", hex: "#2b3a55" },
      { name: "Washed", hex: "#6b7d99" },
    ],
    sizes: sizeApparel,
    description: "Japanese selvedge denim with a straight tapered leg. Raw and unwashed â€” built to age beautifully with every wear.",
    details: ["14oz Japanese selvedge denim", "Straight tapered fit", "Copper rivet reinforcement", "Unsanforized"],
    rating: 4.7,
    reviewCount: 89,
    badge: "new",
  },
  {
    id: "p4",
    name: "Studio Sneaker Low",
    brand: "LUMEN",
    price: 195,
    category: "footwear",
    image: "https://images.pexels.com/photos/18155788/pexels-photo-18155788.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/18155788/pexels-photo-18155788.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/8979071/pexels-photo-8979071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "White", hex: "#f5f5f4" },
      { name: "Black", hex: "#1c1917" },
    ],
    sizes: sizeFootwear,
    description: "A minimalist leather sneaker with a clean silhouette. Hand-finished in Portugal on a Margom sole.",
    details: ["Full-grain Italian leather", "Margom vulcanized sole", "Cotton terry lining", "Made in Portugal"],
    rating: 4.9,
    reviewCount: 341,
    badge: "bestseller",
  },
  {
    id: "p5",
    name: "Runner Trainer",
    brand: "LUMEN",
    price: 160,
    category: "footwear",
    image: "https://images.pexels.com/photos/13236691/pexels-photo-13236691.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/13236691/pexels-photo-13236691.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/13236693/pexels-photo-13236693.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Blue", hex: "#3b5b8c" },
      { name: "Grey", hex: "#78716c" },
    ],
    sizes: sizeFootwear,
    description: "Lightweight performance trainer engineered for daily miles. Responsive foam midsole with breathable knit upper.",
    details: ["Engineered knit upper", "Responsive EVA midsole", "Recycled rubber outsole", "8mm drop"],
    rating: 4.6,
    reviewCount: 127,
  },
  {
    id: "p6",
    name: "Onyx Court Sneaker",
    brand: "LUMEN",
    price: 220,
    compareAtPrice: 260,
    category: "footwear",
    image: "https://images.pexels.com/photos/5930091/pexels-photo-5930091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/5930091/pexels-photo-5930091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/8551781/pexels-photo-8551781.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Black", hex: "#1c1917" },
    ],
    sizes: sizeFootwear,
    description: "A premium court silhouette in tonal black. Nappa leather upper with a cushioned footbed for all-day comfort.",
    details: ["Nappa leather upper", "Memory foam insole", "Tonal stitching", "Made in Italy"],
    rating: 4.8,
    reviewCount: 76,
    badge: "limited",
  },
  {
    id: "p7",
    name: "Bifold Leather Wallet",
    brand: "LUMEN",
    price: 89,
    category: "accessories",
    image: "https://images.pexels.com/photos/33109351/pexels-photo-33109351.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/33109351/pexels-photo-33109351.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/33242820/pexels-photo-33242820.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Cognac", hex: "#8b5e34" },
      { name: "Black", hex: "#1c1917" },
    ],
    sizes: sizeOneSize,
    description: "A slim bifold wallet vegetable-tanned in Tuscany. Six card slots and a full-length note pocket in under 10mm.",
    details: ["Vegetable-tanned leather", "6 card slots", "Slim profile", "Edge-painted finish"],
    rating: 4.7,
    reviewCount: 198,
    badge: "bestseller",
  },
  {
    id: "p8",
    name: "Card Holder Minimal",
    brand: "LUMEN",
    price: 45,
    category: "accessories",
    image: "https://images.pexels.com/photos/33109341/pexels-photo-33109341.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/33109341/pexels-photo-33109341.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Tan", hex: "#b88b65" },
      { name: "Black", hex: "#1c1917" },
    ],
    sizes: sizeOneSize,
    description: "A featherweight card holder for the essentials. Four card slots and a center pocket for folded notes.",
    details: ["Full-grain leather", "4 card slots", "Center pocket", "RFID-protected"],
    rating: 4.6,
    reviewCount: 64,
    badge: "new",
  },
  {
    id: "p9",
    name: "Leather Belt Heritage",
    brand: "LUMEN",
    price: 75,
    category: "accessories",
    image: "https://images.pexels.com/photos/9807758/pexels-photo-9807758.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/9807758/pexels-photo-9807758.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/9807760/pexels-photo-9807760.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Brown", hex: "#6b4423" },
      { name: "Black", hex: "#1c1917" },
    ],
    sizes: ["30", "32", "34", "36", "38"],
    description: "A full-grain leather belt with a solid brass buckle. Cut from a single hide, built to outlast trends.",
    details: ["Full-grain bridle leather", "Solid brass buckle", "1.25 inch width", "Made in USA"],
    rating: 4.8,
    reviewCount: 142,
  },
  {
    id: "p10",
    name: "Ceramic Diffuser Set",
    brand: "LUMEN",
    price: 58,
    category: "home",
    image: "https://images.pexels.com/photos/4202326/pexels-photo-4202326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/4202326/pexels-photo-4202326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/8015786/pexels-photo-8015786.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "White", hex: "#f5f5f4" },
    ],
    sizes: sizeOneSize,
    description: "A hand-poured ceramic diffuser with a custom-blended fragrance. Cedar, sandalwood, and a whisper of vetiver.",
    details: ["Hand-poured ceramic vessel", "Custom fragrance blend", "Reed diffuser sticks", "3 month lifespan"],
    rating: 4.5,
    reviewCount: 38,
    badge: "new",
  },
  {
    id: "p11",
    name: "Botanical Soap Bar",
    brand: "LUMEN",
    price: 18,
    category: "home",
    image: "https://images.pexels.com/photos/9475426/pexels-photo-9475426.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/9475426/pexels-photo-9475426.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Natural", hex: "#e7e5e4" },
    ],
    sizes: sizeOneSize,
    description: "A cold-process soap bar with activated charcoal and shea butter. Cleanses deeply without stripping.",
    details: ["Cold-process formula", "Activated charcoal", "Shea butter enriched", "Vegan and cruelty-free"],
    rating: 4.7,
    reviewCount: 51,
  },
  {
    id: "p12",
    name: "Minimal Desk Organizer",
    brand: "LUMEN",
    price: 42,
    compareAtPrice: 55,
    category: "home",
    image: "https://images.pexels.com/photos/20588031/pexels-photo-20588031.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    images: [
      "https://images.pexels.com/photos/20588031/pexels-photo-20588031.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "https://images.pexels.com/photos/27307285/pexels-photo-27307285.png?auto=compress&cs=tinysrgb&h=650&w=940",
    ],
    colors: [
      { name: "Oak", hex: "#c4a882" },
      { name: "Black", hex: "#1c1917" },
    ],
    sizes: sizeOneSize,
    description: "A solid oak desk organizer that corrals the everyday â€” phone, pens, cards, and keys in one elegant block.",
    details: ["Solid white oak", "Natural oil finish", "Felt-lined slots", "Handmade in Denmark"],
    rating: 4.6,
    reviewCount: 29,
    badge: "sale",
  },
];

export const heroImages = [
  "https://images.pexels.com/photos/33401555/pexels-photo-33401555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "https://images.pexels.com/photos/7450781/pexels-photo-7450781.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "https://images.pexels.com/photos/8499115/pexels-photo-8499115.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
];

export const editorialImage = "https://images.pexels.com/photos/5839958/pexels-photo-5839958.jpeg?auto=compress&cs=tinysrgb&h=650&w=940";

